### ISSUE TITLE
[BUG] macos 13.2.1 下提示 zsh: segmentation fault

### ISSUE THREAD

**Issue by 1zilc** [foamzou/nettop-line#1]
感谢提供nettop-line这么方便的脚本，它一直作为我程序的流量监控脚本在后台调用，当我升级macos13之后，出现了上述错误，请问能帮忙看看不，非常感谢！

```bash
./nettop-line -P -d -L 0 -J bytes_in,bytes_out -t external -s 1 -c
zsh: segmentation fault  ./nettop-line -P -d -L 0 -J bytes_in,bytes_out -t external -s 1 -c
```

**Comment by foamzou** [comment]
@1zilc 没想到还真有人用。
你去掉 upx 压缩就行，build 完直接用。

**Comment by 1zilc** [comment]
好的，十分感谢❤️
<img width="457" alt="image" src="https://user-images.githubusercontent.com/44715458/219032112-7898a967-cada-45f3-b9e8-c12d942222bb.png">
可以了
